services:
  backend:
    container_name: ydenn_backend
    image: node:alpine
    working_dir: /home/node/app
    env_file:
      - ./backend/.env
    command: ["sh", "-c", "npm install && node app.js"]
    volumes:
      - type: bind
        source: ./backend/src
        target: /home/node/app
      - type: bind
        source: ./certs/api.ydenn.fr
        target: /etc/nginx/certs/api.ydenn.fr
    expose:
      - 3000
    ports:
      - "3000:3000"

  alcma_nginx-1:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./certs/api.alcma.fr
        target: /etc/nginx/certs/api.alcma.fr
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
