version: "3.8"
services:
  node:
    container_name: ydenn-backend
    image: "node:latest"
    working_dir: /home/node/app
    env_file:
      - .env
    command:
      - /bin/sh
      - "-c"
      - "npm install && npm start"
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - "./src:/home/node/app"
